### ISSUE TITLE
feature request: show emote name on mouseover

### ISSUE THREAD

**Issue by thiccocado** [4chanmotes/4chanmotes.github.io#3]
it would be nice if it said the name of the emote when you mouse over it in the emote window and when you mouse over the ones in posts

i.e. mouse over the bane emote and alt text appears that says :bane:

**Comment by 4chanmotes** [comment]
this is already implemented
![mouseover](https://user-images.githubusercontent.com/103033931/161864889-1480a217-6008-41a2-864c-821089462252.png)
does it not work?

**Comment by thiccocado** [comment]
oh you know what I do see that. did you add that in the latest update? I don't think that worked before today.

**Comment by 4chanmotes** [comment]
> did you add that in the latest update? I don't think that worked before today.

I added it 3 days ago, it's good that it works
