### ISSUE TITLE
feature request: add a checkbox to hide anime emotes in the emote window

### ISSUE THREAD

**Issue by thiccocado** [4chanmotes/4chanmotes.github.io#4]
it's fine if I see them in posts but I would never post an anime emote myself. a checkbox or something like that in the emote window would be nice.

**Comment by 4chanmotes** [comment]
soon...

**Comment by 4chanmotes** [comment]
please check if the new version does what you asked for
in settings -> custom tab you can input "#all,/anime" to remove anime emotes from the custom tab

**Comment by thiccocado** [comment]
just tried it out (on chrome/tampermonkey). changed the settings and it didn't do anything at first but I refreshed the page and now it works. thanks.
